#services:
#  file-server:
#    build: .
#    container_name: nginx-file-server
#    ports:
#      - "18080:80"
#    volumes:
#      - ./abc:/usr/share/nginx/html
#    user: root
#    restart: unless-stopped
#
version: '3.8'
services:
  file-server:
    build: .
    container_name: nginx-file-server
    ports:
      - "18180:80"
    volumes:
      - ./files:/usr/share/nginx/html
    user: root
    restart: unless-stopped
    depends_on:
      - openlist
  
  openlist:
    image: openlistteam/openlist:latest-aio
    container_name: openlist-file-server
    ports:
      - "5744:5244"
    volumes:
      - ./files:/data
      - ./openlist_data:/opt/openlist/data
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - ALIST_STORAGE_DIR=/data
    restart: unless-stopped
